apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-dep
  labels:
    depinfo: dep-vote

spec:
  relplicas: 3

  selector:
    matchLabels:
      podinfo: pod-vote

  template:

    metadata:
      name: vote
      labels:
        podinfo: pod-vote
    spec:
      containers:
        - name: vote-cont
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
