apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-dep
  labels:
    depinfo: dep-db
spec:
  selector:
    matchLabels:
      podinfo: pod-db
  replicas: 3

  template:
    metadata:
      name: db
      labels:
        podinfo: pod-db

    spec:
      containers:
        - name: db-cont
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: postgres
